'use strict';

const agreed_header = [
	'vendor_sku',
	'carat',
	'shipping_availability',
	'certificate_lab',
	'certificate_number',
	'orig_certificate_url',
	'shape',
	'cost',
	'cost_per_carat',
	'clarity',
	'color',
	'cut',
	'culet',
	'polish',
	'depth',
	'depth_percent',
	'width',
	'length',
	'length_width_ratio',
	'fluorescence',
	'girdle',
	'girdle_percent',
	'symmetry',
	'table_percent',
	'key_to_symbols',
	'crown_height',
	'crown_angle',
	'pavilion_depth',
	'pavilion_angle',
	'location',
	'lab_grown',
	'orig_primary_image_url',
	'orig_proportions_url',
	'orig_plotting_url',
	'orig_video_url',
	'orig_3d_360_url',
	'orig_alt_image1_url',
	'orig_alt_image2_url',
	'orig_alt_image3_url',
	'orig_video1_url',
	'orig_video2_url'
];

module.exports = agreed_header;