'use strick';

const diamonds = [
    {
        vendor_sku: 'R10-38900',
        carat: 1.03,
        shipping_availability: 'Guaranteed',
        certificate_lab: 'GIA',
        certificate_number: '2205729946',
        orig_certificate_url: 'https://assets.newecx.com/template/assets/GIA-2205729946/certificate.pdf',
        shape: 'CU',
        cost: 4073,
        cost_per_carat: 3954.37,
        clarity: 'SI1',
        color: 'E',
        cut: 'VG',
        culet_size: 'N',
        polish: 'VG',
        depth: 3.63,
        depth_percent: 64.7,
        width: 5.6,
        length: 6.16,
        length_width_ratio: 1.1,
        fluorescence: 'F',
        girdle: 'Slightly Thick to Extremely Thick, Faceted',
        symmetry: 'VG',
        table_percent: 66,
        key_to_symbols: 'Crystal,Needle,Feather',
        lab_grown: 0,
        orig_primary_image_url: 'https://assets.newecx.com/template/assets/GIA-2205729946/primary.jpg',
        orig_proportions_url: 'https://assets.newecx.com/template/assets/GIA-2205729946/cutprofile.jpg',
        orig_plotting_url: 'https://assets.newecx.com/template/assets/GIA-2205729946/plot.jpg',
        orig_video_url: 'https://assets.newecx.com/template/assets/GIA-2205729946/video.mp4',
    },
    {
        vendor_sku: 'E18-12897',
        carat: 5.02,
        certificate_lab: 'IGI',
        certificate_number: '459108837',
        orig_certificate_url: 'https://assets.newecx.com/template/assets/IGI-459108837/certificate.pdf',
        shape: 'EM',
        cost: 17394.3,
        cost_per_carat: 3465,
        clarity: 'VS2',
        color: 'F',
        cut: 'G',
        culet_size: 'N',
        polish: 'EX',
        depth: 4.99,
        depth_percent: 63.2,
        width: 11.02,
        length: 7.9,
        length_width_ratio: 0.72,
        fluorescence: 'N',
        symmetry: 'EX',
        table_percent: 71,
        location: 'belgium',
        lab_grown: 1,
        orig_primary_image_url: 'https://assets.newecx.com/template/assets/IGI-459108837/primary.jpg',
        orig_video_url: 'https://assets.newecx.com/template/assets/IGI-459108837/video.mp4',
        orig_3d_360_url: 'https://labgrowndiamond.s3.amazonaws.com/Video/Viewer4.0/Vision360.html?d=459108837',
    },
];

module.exports = diamonds;